name: MyDrops
main: com.cyprias.mydrops.MyDrops
version: 0.7.0

permissions:
    mydrops.*:
        description: Grant all access.
        default: false
        children:
            mydrops.protect: true
            mydrops.exempt: true
    mydrops.protect:
        description: Protect items dropped by this player.
        default: false
    mydrops.exempt:
        description: Allow these players to pickup protected items.
        default: false